apiVersion: apps/v1
kind: Deployment
metadata:
  name: parker
  namespace: speculaas
spec:
  selector:
    matchLabels:
      run: parker
  replicas: 2
  template:
    metadata:
      labels:
        run: parker
    spec:
      containers:
        - name: parker
          image: ghcr.io/mikemoraned/parker:0.1.1
          env:
            - name: REDIRECT_URL
              value: "https://youtube.com/playlist?list=PLeGZvF0_CoYE26xMJDYGOm7-8LddqCAPh"
            - name: PORT
              value: "8000"
          ports:
            - name: http
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health_check
              port: 8000
          readinessProbe:
            httpGet:
              path: /health_check
              port: 8000

